version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:alpine
    ports:
      - "5455:5432"
    # volumes:
    #   - /data/postgres:/data/postgres
    # env_file:
    #   - docker.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    # volumes:
    #   - /data/pgadmin:/root/.pgadmin
    # env_file:
    #   - docker.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres

networks:
  postgres:
    driver: bridge